---
local_db: sqlite3:/var/vcap/services/celery/celery_node.db
base_dir: /var/vcap/services/celery/
celeryctl: celeryctl
celeryd: celeryd
mbus: nats://localhost:4222
log_level: DEBUG
local_ip: 127.0.0.1
available_memory: 4096
max_memory: 16
node_id: celery_node_1
pid: /var/vcap/sys/run/celery_node.pid
